# Generated by Django 4.2.7 on 2023-11-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purplewiguser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
