# Generated by Django 4.2.7 on 2023-11-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_purplewiguser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
