# Generated by Django 4.2.7 on 2023-12-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_service_serviceregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceregistration',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
