# Generated by Django 4.2.7 on 2023-12-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_serviceregistration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceregistration',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
